###
GET http://localhost:5000/auth
Content-Type: application/json

{
  "uname": "issei2018",
  "pwd": "aaaa"
}

###
POST http://localhost:5000/auth/register
Content-Type: application/json

{
  "uname": "robocon321",
  "pwd": "badc",
  "email": "robocon321n@gmail.com"
}

### 
POST http://localhost:5000/auth/login
Content-Type: application/json

{
  "uname": "robocon321",
  "pwd": "badc",
  "email": "robocon321n@gmail.com"
}

###
GET http://localhost:5000/auth
Content-Type: application/json
Authorization:  Print eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjE2MzE4MTQ3MzkwNjcsImlhdCI6MTYzMTgxNzMxM30.zPLtlobU_OjgPEAofigMJrg_r_aVDKUx4xpUmEltqik

###
GET http://localhost:5000/admin/account
Content-Type: application/json
Authorization:  Print eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjE2MzE4MTQ3MzkwNjcsImlhdCI6MTYzMTgxNzMxM30.zPLtlobU_OjgPEAofigMJrg_r_aVDKUx4xpUmEltqik

###
POST http://localhost:5000/admin/account
Content-Type: application/json
Authorization:  Print eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjE2MzE4MTQ3MzkwNjcsImlhdCI6MTYzMTgxNzMxM30.zPLtlobU_OjgPEAofigMJrg_r_aVDKUx4xpUmEltqik

{
  "uname": "robocon32123",
  "pwd": "lie54kd9",
  "full_name": "Nguyen Cong Nguyen",
  "email": "robocon321n@gmail.com",
  "phone": "0354512411",
  "sex": "false",
  "birthday": 1632562489826
}

###
PUT http://localhost:5000/admin/account
Content-Type: application/json
Authorization:  Print eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjE2MzE4MTQ3MzkwNjcsImlhdCI6MTYzMTgxNzMxM30.zPLtlobU_OjgPEAofigMJrg_r_aVDKUx4xpUmEltqik

{
  "_id": 1632565112911,
  "pwd": "123bd41234",
  "full_name": "Robocon",
  "email": "robocon321n@gmail.com",
  "phone": "03545454454",
  "sex": "false",
  "birthday": 1632562489999
}

###
DELETE  http://localhost:5000/admin/account
Content-Type: application/json
Authorization:  Print eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjE2MzE4MTQ3MzkwNjcsImlhdCI6MTYzMTgxNzMxM30.zPLtlobU_OjgPEAofigMJrg_r_aVDKUx4xpUmEltqik

{
  "id": 1632818127982
}

### category

###
GET http://localhost:5000/admin/category?&search=
Content-Type: application/json
Authorization:  Print eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjE2MzE4MTQ3MzkwNjcsImlhdCI6MTYzMTgxNzMxM30.zPLtlobU_OjgPEAofigMJrg_r_aVDKUx4xpUmEltqik

###
POST http://localhost:5000/admin/category
Content-Type: application/json
Authorization:  Print eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjE2MzE4MTQ3MzkwNjcsImlhdCI6MTYzMTgxNzMxM30.zPLtlobU_OjgPEAofigMJrg_r_aVDKUx4xpUmEltqik

{
  "title": "Item 14",
  "parent_id": 1632967075715,
  "display_order": 3,
  "meta_keyword": "Keyword",
  "meta_descrp": "Description",
  "meta_title": "Title",
  "slug": "item14",
  "icon": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Flat_tick_icon.svg/1200px-Flat_tick_icon.svg.png"
}

###
PUT http://localhost:5000/admin/category
Content-Type: application/json
Authorization:  Print eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjE2MzE4MTQ3MzkwNjcsImlhdCI6MTYzMTgxNzMxM30.zPLtlobU_OjgPEAofigMJrg_r_aVDKUx4xpUmEltqik

{
  "_id": 1632911712843,
  "title": "Điện thoại",
  "display_order": 3,
  "meta_keyword": "Keyword",
  "meta_descrp": "Description",
  "meta_title": "Title update",
  "slug": "phone",
  "icon": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Flat_tick_icon.svg/1200px-Flat_tick_icon.svg.png"
}


### attribute

GET http://localhost:5000/admin/attribute
Content-Type: application/json
Authorization:  Print eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjE2MzE4MTQ3MzkwNjcsImlhdCI6MTYzMTgxNzMxM30.zPLtlobU_OjgPEAofigMJrg_r_aVDKUx4xpUmEltqik

###
POST http://localhost:5000/admin/attribute
Content-Type: application/json
Authorization:  Print eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjE2MzE4MTQ3MzkwNjcsImlhdCI6MTYzMTgxNzMxM30.zPLtlobU_OjgPEAofigMJrg_r_aVDKUx4xpUmEltqik

{
  "attributes": [{
    "title": "Attr 1",
    "category_id": 1632911712843,
    "datatype": 0
  },{
    "title": "Attr 2",
    "category_id": 1632911712843,
    "datatype": 0
  }, {
    "title": "Attr 1",
    "category_id": 1632911712843,
    "datatype": 0
  },{
    "title": "Attr 3",
    "category_id": 1632911712843,
    "datatype": 0
  }]
}

###
PUT http://localhost:5000/admin/attribute
Content-Type: application/json
Authorization:  Print eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjE2MzE4MTQ3MzkwNjcsImlhdCI6MTYzMTgxNzMxM30.zPLtlobU_OjgPEAofigMJrg_r_aVDKUx4xpUmEltqik

{
  "attributes": [{
    "title": "Attr 14",
    "category_id": 1632911712843,
    "datatype": 0
  },{
    "title": "Attr 12",
    "category_id": 1632911712843,
    "datatype": 0
  }, {
    "title": "Attr 15",
    "category_id": 1632911712843,
    "datatype": 0
  },{
    "title": "Attr 13",
    "category_id": 1632911712843,
    "datatype": 0
  }]
}

### shop
GET http://localhost:5000/admin/shop?search=
Content-Type: application/json
Authorization:  Print eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjE2MzE4MTQ3MzkwNjcsImlhdCI6MTYzMTgxNzMxM30.zPLtlobU_OjgPEAofigMJrg_r_aVDKUx4xpUmEltqik

###
POST http://localhost:5000/admin/shop
Content-Type: application/json
Authorization:  Print eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjE2MzE4MTQ3MzkwNjcsImlhdCI6MTYzMTgxNzMxM30.zPLtlobU_OjgPEAofigMJrg_r_aVDKUx4xpUmEltqik

{
  "title": "Shop 2",
  "descrp": "Descrp",
  "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Image_created_with_a_mobile_phone.png/1200px-Image_created_with_a_mobile_phone.png",
  "meta_keyword": "Keyword",
  "meta_descrp": "Description",
  "meta_title": "Title",
  "slug": "slug3"
}

### 
PUT http://localhost:5000/admin/shop
Content-Type: application/json
Authorization:  Print eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjE2MzE4MTQ3MzkwNjcsImlhdCI6MTYzMTgxNzMxM30.zPLtlobU_OjgPEAofigMJrg_r_aVDKUx4xpUmEltqik

{
  "_id": 1633512561578,
  "title": "Shop 2",
  "descrp": "Descrp",
  "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Image_created_with_a_mobile_phone.png/1200px-Image_created_with_a_mobile_phone.png",
  "meta_keyword": "Keyword",
  "meta_descrp": "Description",
  "meta_title": "Title",
  "slug": "slug"
}

### product

GET http://localhost:5000/admin/product?search=
Content-Type: application/json
Authorization:  Print eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjE2MzE4MTQ3MzkwNjcsImlhdCI6MTYzMTgxNzMxM30.zPLtlobU_OjgPEAofigMJrg_r_aVDKUx4xpUmEltqik

###
POST http://localhost:5000/admin/product
Content-Type: application/json
Authorization:  Print eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjE2MzE4MTQ3MzkwNjcsImlhdCI6MTYzMTgxNzMxM30.zPLtlobU_OjgPEAofigMJrg_r_aVDKUx4xpUmEltqik

{
  "title": "Iphone X",
  "descrp": "Mô tả",
  "category_id": 163958483984,
  "quantity": 100,
  "detail": "Detail",
  "meta_keyword": "K1",
  "meta_descrp": "Descrip",
  "meta_title": "meta title",
  "slug": "sjke0",
  "include_vat": true,
  "shop_id": 92384982333,
  "warrently": "3 tháng"
}

###
POST http://localhost:5000/admin/product
Content-Type: application/json
Authorization:  Print eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjE2MzE4MTQ3MzkwNjcsImlhdCI6MTYzMTgxNzMxM30.zPLtlobU_OjgPEAofigMJrg_r_aVDKUx4xpUmEltqik

{
  "title": "Iphone SE",
  "descrp": "Mô tả",
  "category_id": 163958483984,
  "quantity": 100,
  "detail": "Detail",
  "meta_keyword": "K1",
  "meta_descrp": "Descrip",
  "meta_title": "meta title",
  "slug": "add",
  "include_vat": true,
  "shop_id": 92384982444,
  "warrently": "5 tháng",
  "tags": "a,b,c,d"
}

###
POST http://localhost:5000/admin/product
Content-Type: application/json
Authorization:  Print eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjE2MzE4MTQ3MzkwNjcsImlhdCI6MTYzMTgxNzMxM30.zPLtlobU_OjgPEAofigMJrg_r_aVDKUx4xpUmEltqik

{
  "title": "Iphone XS",
  "descrp": "Mô tả",
  "category_id": 163958483984,
  "quantity": 100,
  "detail": "Detail",
  "meta_keyword": "K1",
  "meta_descrp": "Descrip",
  "meta_title": "meta title",
  "slug": "noodo",
  "include_vat": true,
  "shop_id": 9283498238,
  "warrently": "5 tháng",
  "tags": "a,b,d,e,p"
}

###
PUT http://localhost:5000/admin/product
Content-Type: application/json
Authorization:  Print eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjE2MzE4MTQ3MzkwNjcsImlhdCI6MTYzMTgxNzMxM30.zPLtlobU_OjgPEAofigMJrg_r_aVDKUx4xpUmEltqik

{
  "_id": 1633753094397,
  "title": "Iphone XSX",
  "descrp": "Mô tả",
  "category_id": 163958483984,
  "quantity": 200,
  "detail": "Detail",
  "meta_keyword": "K1",
  "meta_descrp": "Descrip",
  "meta_title": "meta title",
  "slug": "noodo",
  "include_vat": true,
  "shop_id": 9283498238,
  "warrently": "5 tháng",
  "tags": "a,b,h,p"
}

### product attribute value
GET http://localhost:5000/admin/option-product-title
Content-Type: application/json
Authorization:  Print eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjE2MzE4MTQ3MzkwNjcsImlhdCI6MTYzMTgxNzMxM30.zPLtlobU_OjgPEAofigMJrg_r_aVDKUx4xpUmEltqik

###
POST http://localhost:5000/admin/option-product-title
Content-Type: application/json
Authorization:  Print eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjE2MzE4MTQ3MzkwNjcsImlhdCI6MTYzMTgxNzMxM30.zPLtlobU_OjgPEAofigMJrg_r_aVDKUx4xpUmEltqik

{
  "optProductTitles": [
    {
      "product_id": 1633753076519,
      "title": "Màu",
      "datatype": 1
    },{
      "product_id": 1633753076519,
      "title": "RAM",
      "datatype": 2
    }
  ]
}

### option product value
GET http://localhost:5000/admin/option-product-value
Content-Type: application/json
Authorization:  Print eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjE2MzE4MTQ3MzkwNjcsImlhdCI6MTYzMTgxNzMxM30.zPLtlobU_OjgPEAofigMJrg_r_aVDKUx4xpUmEltqik

###
POST http://localhost:5000/admin/option-product-value
Content-Type: application/json
Authorization:  Print eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjE2MzE4MTQ3MzkwNjcsImlhdCI6MTYzMTgxNzMxM30.zPLtlobU_OjgPEAofigMJrg_r_aVDKUx4xpUmEltqik

{
  "listOptProductValues": [
    [
      {
        "opt_title_id": 1633939066996,
        "text_value": "Xanh",
        "opt_real_price": 12290000,
        "opt_sale_price": 12190000,
        "avatar": "https://interactive-examples.mdn.mozilla.net/media/cc0-images/grapefruit-slice-332-332.jpg",
        "imgs": "https://interactive-examples.mdn.mozilla.net/media/cc0-images/grapefruit-slice-332-332.jpg,https://interactive-examples.mdn.mozilla.net/media/cc0-images/grapefruit-slice-332-332.jpg,https://interactive-examples.mdn.mozilla.net/media/cc0-images/grapefruit-slice-332-332.jpg"
      },
      {
        "opt_title_id": 1633939068297,
        "text_value": "3G",
        "opt_real_price": 12290000,
        "opt_sale_price": 12190000,
        "avatar": "https://interactive-examples.mdn.mozilla.net/media/cc0-images/grapefruit-slice-332-332.jpg",
        "imgs": "https://interactive-examples.mdn.mozilla.net/media/cc0-images/grapefruit-slice-332-332.jpg,https://interactive-examples.mdn.mozilla.net/media/cc0-images/grapefruit-slice-332-332.jpg,https://interactive-examples.mdn.mozilla.net/media/cc0-images/grapefruit-slice-332-332.jpg"
      }
    ],
    [
      {
        "opt_title_id": 1633939066996,
        "text_value": "Vàng",
        "opt_real_price": 14290000,
        "opt_sale_price": 14190000,
        "avatar": "https://interactive-examples.mdn.mozilla.net/media/cc0-images/grapefruit-slice-332-332.jpg",
        "imgs": "https://interactive-examples.mdn.mozilla.net/media/cc0-images/grapefruit-slice-332-332.jpg,https://interactive-examples.mdn.mozilla.net/media/cc0-images/grapefruit-slice-332-332.jpg,https://interactive-examples.mdn.mozilla.net/media/cc0-images/grapefruit-slice-332-332.jpg"
      },
      {
        "opt_title_id": 1633939068297,
        "text_value": "4G",
        "opt_real_price": 14290000,
        "opt_sale_price": 14190000,
        "avatar": "https://interactive-examples.mdn.mozilla.net/media/cc0-images/grapefruit-slice-332-332.jpg",
        "imgs": "https://interactive-examples.mdn.mozilla.net/media/cc0-images/grapefruit-slice-332-332.jpg,https://interactive-examples.mdn.mozilla.net/media/cc0-images/grapefruit-slice-332-332.jpg,https://interactive-examples.mdn.mozilla.net/media/cc0-images/grapefruit-slice-332-332.jpg"
      }
    ]
  ]
}

### product option

GET http://localhost:5000/admin/option-product
Content-Type: application/json
Authorization:  Print eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjE2MzE4MTQ3MzkwNjcsImlhdCI6MTYzMTgxNzMxM30.zPLtlobU_OjgPEAofigMJrg_r_aVDKUx4xpUmEltqik

###
POST http://localhost:5000/admin/option-product
Content-Type: application/json
Authorization:  Print eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjE2MzE4MTQ3MzkwNjcsImlhdCI6MTYzMTgxNzMxM30.zPLtlobU_OjgPEAofigMJrg_r_aVDKUx4xpUmEltqik

{
  "group": [
    [
      {
        "product_title" : {
          "product_id": 1633753076519,
          "title": "ROM",
          "datatype": 1
        },
        "product_value" : {
          "number_value": 1,
          "opt_real_price": 122,
          "opt_sale_price": 100,
          "quantity": 10,
          "avatar": "https://www.pixsy.com/wp-content/uploads/2021/04/ben-sweet-2LowviVHZ-E-unsplash-1.jpeg"
        }
      }
    ],
    [
      {
        "product_title" : {
          "product_id": 1633753076519,
          "title": "ROM",
          "datatype": 1
        },
        "product_value" : {
          "number_value": 1,
          "opt_real_price": 122,
          "opt_sale_price": 100,
          "quantity": 10,
          "avatar": "https://www.pixsy.com/wp-content/uploads/2021/04/ben-sweet-2LowviVHZ-E-unsplash-1.jpeg"
        }
      }
    ]  ]
}