GET http://localhost:5000/

###
GET http://localhost:5000/auth
Content-Type: application/json

{
  "uname": "",
  "pwd": ""
}

###
POST http://localhost:5000/auth/register
Content-Type: application/json

{
  "uname": "robocon321",
  "pwd": "badc",
  "email": "robocon321n@gmail.com"
}

### 
POST http://localhost:5000/auth/login
Content-Type: application/json

{
  "uname": "tana",
  "pwd": "badc",
  "email": "robocon321n@gmail.com"
}

###
GET http://localhost:3000/auth 
Content-Type: application/json
Authorization:  Print eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjE2MzE4MTQ3MzkwNjcsImlhdCI6MTYzMTgxNzMxM30.zPLtlobU_OjgPEAofigMJrg_r_aVDKUx4xpUmEltqik
